esphome:
  name: fancontrol
  on_boot:
    priority: -100
    then:
      - lambda: |-
          id(itho_hub).register_state_sensor(id(fan_state_numeric));
          id(itho_hub).register_speed_sensor(id(fanspeed));
          id(itho_hub).register_timer_sensor(id(fan_timer));
          id(itho_hub).register_controller_sensor(id(last_controller));
      - delay: 100ms
      - lambda: |-
          // Send Low command after sensors are registered to sync ESP with fan
          id(itho_hub).send_command(1);
          ESP_LOGI("itho", "Sent Low command on boot for synchronization");

esp8266:
  board: d1_mini
  framework:
    version: recommended

external_components:
  - source:
      type: local
      path: components
    components: [itho_fan]

itho_fan:
  id: itho_hub
  device_id: "10,87,81"
  device_name: "New ESP"
  interrupt_pin: D1
  remote_ids:
    - remote_id: "51,40,61"
      room_name: "Badkamer"

button:
  - platform: template
    name: "Fan Low"
    icon: "mdi:fan-speed-1"
    on_press:
      - lambda: |-
          id(itho_hub).send_command(1);
  
  - platform: template
    name: "Fan Medium"
    icon: "mdi:fan-speed-2"
    on_press:
      - lambda: |-
          id(itho_hub).send_command(2);
  
  - platform: template
    name: "Fan High"
    icon: "mdi:fan-speed-3"
    on_press:
      - lambda: |-
          id(itho_hub).send_command(3);
  
  - platform: template
    name: "Join Remote"
    icon: "mdi:remote-desktop"
    on_press:
      - lambda: |-
          id(itho_hub).send_join();
  
  - platform: template
    name: "Leave Remote"
    icon: "mdi:close-network"
    on_press:
      - lambda: |-
          id(itho_hub).send_leave();

sensor:
  - platform: template
    name: "Fan State"
    id: fan_state_numeric
    icon: "mdi:fan"

text_sensor:
  - platform: template
    name: "Fan Speed"
    id: fanspeed
    icon: "mdi:fan"
    
  - platform: template
    name: "Fan Timer Remaining"
    id: fan_timer
    icon: "mdi:timer"
    
  - platform: template
    name: "Last Control Source"
    id: last_controller
    icon: "mdi:remote"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  min_auth_mode: WPA2
  ap:
    ssid: "FALLBACK AP"
    password: "jdsh348201"

captive_portal:

logger:
  level: DEBUG

api:
  on_client_connected:
    then:
      - lambda: |-
          // Handle Home Assistant connection (republish current state only)
          ESP_LOGI("itho", "Home Assistant connected");
          id(itho_hub).on_homeassistant_connected();

ota:
  - platform: esphome
    on_begin:
      then:
        - lambda: |-
            ESP_LOGI("custom", "Disabling interrupts for OTA");
            if (id(itho_hub).get_interrupt_pin() != nullptr) {
              id(itho_hub).get_interrupt_pin()->detach_interrupt();
            }

# For Home Assistant template fan configuration example, see README.md
