esphome:
  name: fancontrol
  on_boot:
    then: 
      - fan.turn_on: 
          id: itho_fan_component
          speed: 1

esp8266:
  board: d1_mini
  framework:
    version: recommended

external_components:
  - source:
      type: local
      path: components
    components: [itho_fan]

itho_fan:
  id: itho_hub
  device_id: "10,87,81"
  interrupt_pin: D1
  remote_ids:
    - remote_id: "51,40,61"
      room_name: "Badkamer"
    - remote_id: "73,82,11"
      room_name: "Toilet"

fan:
  - platform: itho_fan
    id: itho_fan_component
    name: "Itho Ventilation"

text_sensor:
  - platform: template
    name: "Fan Timer Remaining"
    id: fan_timer
    icon: "mdi:timer"
    lambda: |-
      if (id(itho_hub).get_timer() > 0) {
        int minutes = id(itho_hub).get_timer() / 60;
        int seconds = id(itho_hub).get_timer() % 60;
        char buffer[20];
        sprintf(buffer, "%d:%02d", minutes, seconds);
        return {buffer};
      }
      return {"0"};
    update_interval: 1s
    
  - platform: template
    name: "Last Control Source"
    id: last_controller
    icon: "mdi:remote"
    lambda: |-
      return {id(itho_hub).get_last_id()};
    update_interval: 1s

wifi:
  ssid: <YOURSSID>
  password: <YOURPASSWORD>
  ap:
    ssid: "FALLBACK AP"
    password: "jdsh348201"

captive_portal:

logger:
  level: DEBUG

api:

ota:
  on_begin:
    then:
      - lambda: |-
          ESP_LOGI("custom", "Disabling interrupts for OTA");
          detachInterrupt(D1);
